name: publish

on:
  schedule:
    # every 18:21 UTC
    - cron: "21 18 * * 0"
    - cron: "21 18 * * 1"
    - cron: "21 18 * * 2"
    - cron: "21 18 * * 3"
    - cron: "21 18 * * 4"
    - cron: "21 18 * * 5"
    - cron: "21 18 * * 6"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: checkout build scripts
        uses: actions/checkout@v4
        with:
          repository: onlinegears/private-buildah-images
          path: ./private-buildah-images
          ssh-key: ${{ secrets.PRIVATE_BUILDAH_IMAGES }}
      - name: login ghcr.io
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: build
        run: |
          cd ./private-buildah-images
          for n in core gui build-pa-modules lxde browser selenium puppeteer dev; do
            echo $n
            ./build.sh $n
          done
      - name: push to ghcr.io
        run: |
          for n in core lxde browser selenium puppeteer dev; do
            echo $n
            podman push repo:$n docker://ghcr.io/${{ github.actor }}/repo:$n
          done
      - name: push to docker.io
        run: |
          podman login -u ${{ secrets.DCKR_USER }} -p ${{ secrets.DCKR_PAT }} docker.io
          for n in selenium puppeteer dev; do
            echo $n
            podman push repo:$n docker://docker.io/${{ secrets.DCKR_USER }}/ghrepo:$n
          done
      - name: push to docker.io f
        run: |
          podman login -u ${{ secrets.DCKR_USER }} -p ${{ secrets.DCKR_PAT }} docker.io
          for n in selenium puppeteer dev; do
            echo $n
            podman create --name f repo:$n
            podman export f | podman import - f:$n
            podman push f:$n docker://docker.io/${{ secrets.DCKR_USER }}/ghrepo-f:$n
            podman rm f
            podman rmi f:$n
          done
